### ISSUE TITLE
List the Name of all the Edibles in edibles.json file in Readme.md

### ISSUE THREAD

**Issue by Inventor77** [Inventor77/Nutiveal-Nutrition-Data#11]
- Give sub title **All Edibles** in the Readme file 
- Go to the edibles.json file inside the data folder
- List out all the names of edibles in the JSON file in the Pascal case under the All Edibles title

*********************************************************
# Example 
*********************************************************

## All Edibles 
- Carrot 
- Banana
- WaterMelon
- MilkTea
- BlackTea

**Comment by Alcadeus0** [comment]
hi can i work on this issue?

**Comment by Inventor77** [comment]
Sure go ahead with this issue
