### ISSUE TITLE
Adding Guidelines  of Hacktoberfest to the readme file

### ISSUE THREAD

**Issue by Sachinmalve** [Inventor77/Nutiveal-Nutrition-Data#12]

**Comment by Shivashish-rwt** [comment]
I can do it. Can u assign this to me.

**Comment by Inventor77** [comment]
go ahead

**Comment by Inventor77** [comment]
You have to add the guidelines and other important pointers to readme file

**Comment by charu210703** [comment]
if its still open, can you assign this to me?

**Comment by Inventor77** [comment]
@charu210703 go ahead and make some meaningful changes to the guidelines in readme.md

**Comment by Inventor77** [comment]
@charu210703 You can add Hactoberfest22 banner in readme.md

**Comment by charu210703** [comment]
> @charu210703 You can add Hactoberfest22 banner in readme.md

banner as in the image?

**Comment by Inventor77** [comment]
@charu210703.. Yupp the hactoberfest Logo for this year

**Comment by charu210703** [comment]
Done! I have done the PR #47. Thank you for letting me contribute.
