### ISSUE TITLE
List the Name of all the Edibles in nutrition.json file in Readme.md

### ISSUE THREAD

**Issue by Inventor77** [Inventor77/Nutiveal-Nutrition-Data#18]
- Give sub title **All Edibles in nutrients.json** in the Readme file 
- Go to the nutrients.json file inside the data folder
- List out all the names of edibles in the JSON file in the Pascal case under the All Edibles title

*********************************************************
# Example 
*********************************************************

## All Edibles in nutrients.json
- Carrot 
- Banana
- WaterMelon
- MilkTea
- BlackTea

**Comment by ShivanshDengla** [comment]
Hey,
I looked through the nutrients.json file and there i could see only 3 edible items, tuna, chicken liver, beef liver. Should i add only these three in the readme file?

**Comment by Sscuber03** [comment]
Can this issue be assigned to me?

**Comment by Inventor77** [comment]
@ShivanshDengla Sorry I have mentioned te wrong file name please go for the [nutrition.json](https://github.com/Inventor77/Nutiveal-Nutrition-Data/blob/main/data/nutrition.json) file.

**Comment by Inventor77** [comment]
@Sscuber03 You can go for other issue

**Comment by ShivanshDengla** [comment]
> @ShivanshDengla Sorry I have mentioned te wrong file name please go for the [nutrition.json](https://github.com/Inventor77/Nutiveal-Nutrition-Data/blob/main/data/nutrition.json) file.

okayy got it, ill list the names from this files

**Comment by Inventor77** [comment]
@ShivanshDengla @Sscuber03 Please star this repository

**Comment by ShivanshDengla** [comment]
> @ShivanshDengla @Sscuber03 Please star this repository

Done, so there are around 8000 items there, how many should i list?

**Comment by ShivanshDengla** [comment]
@Sscuber03 i made a pull request #19 do check it and let me know should i add more? i am new to it so please forgive for any mistakes.
Thanks

**Comment by Inventor77** [comment]
make a new md file and move all items and make a complete list of 8000+ items there 
name that file nutrition.json

**Comment by Inventor77** [comment]
Raise new issue for that, and how many you have to do for hactoberfest

**Comment by Sscuber03** [comment]
@Inventor77 I have completed the issue, with 8789 edible names. Can this be assigned to me?, and if so, where to keep those names, in readme, or should i create another markdown file?

**Comment by Sscuber03** [comment]
> @ShivanshDengla @Sscuber03 Please star this repository

done!

**Comment by Inventor77** [comment]
@Sscuber03  Thanks a lot for the star to this repo, Please create a new Markdown file and go with it I am assigning you this issue

**Comment by Sscuber03** [comment]
@Inventor77 Please do check the pr. Let me know if there is any problem, so that i can fix it.
